POST http://localhost:3333/report-loader/main-info
Content-Type: application/json
Authorization: Basic user user

{
  "okpo": 1234567890,
  "name": "name"
}

###

GET http://localhost:3333/report-loader/rest/api/main-info


###

POST http://localhost:3333/report-loader/rest/api/main-info
Content-Type: application/json

{
  "okpo": 1234567890,
  "name": "name"
}

###

POST http://localhost:3333/report-loader/rest/api/upload
Content-Type: multipart/form-data

###
GET http://localhost:3333/report-loader/rest/api/check

###
POST http://localhost:3333/report-loader/rest/api/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"

field-value
--WebAppBoundary--

###